framework:
    templating: { engines: [twig] }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email: {address: "fosub@localhost", sender_name: FOSUB}
#    from_email:
#        address: "%mailer_user%"
#        sender_name: "%mailer_user%"
    use_flash_notifications: false